### ISSUE TITLE
More info on how to build

### ISSUE THREAD

**Issue by iedmrc** [DevUtilsApp/DevUtils-app#5]
Could you please provide more info on how to build? Especially after `Bootstrap carthage: carthage bootstrap --platform macOS` step. Thanks!

**Comment by micheld93** [comment]
Even `Bootstrap carthage: carthage bootstrap --platform macOS` fails on my computer: 
`Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file."`

Xcode is not my cup of tea. It's version 12. The build fails as well: 
- No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "4XXXXXXXXX" with a private key was found.
- 
Showing Recent Messages
No account for team "4XXXXXXXXX". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

I added my ID and I think I set everything to "Run locally". Need to investigate it further. I believe it's just a question of right settings that need to be done.

**Comment by danielewood** [comment]
```
git clone https://github.com/DevUtilsApp/DevUtils-app
cd DevUtils-app
carthage bootstrap --platform macOS
```

After that, you have to set the Xcode signing certificate to your own, if you build as a local only signing, it cant sign the non-embedded frameworks.

**Comment by trungdq88** [comment]
> `Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file."`

Make sure you run `carthage bootstrap` where the Cartfile is.

@iedmrc Is there any specific step that you have a problem? I don't have access to any other version of Swift/Xcode so I cannot provide detailed steps. The project should be run-able as any other Xcode project. Maybe [this comment](https://news.ycombinator.com/item?id=24615001) will help?

**Comment by micheld93** [comment]
> After that, you have to set the Xcode signing certificate to your own, if you build as a local only signing, it cant sign the non-embedded frameworks.

@danielewood Thanks for the help. Do I need to be an enrolled Apple Developer for 99€ to get those code signing certificates?

**Comment by glenvan** [comment]
> > After that, you have to set the Xcode signing certificate to your own, if you build as a local only signing, it cant sign the non-embedded frameworks.
> 
> @danielewood Thanks for the help. Do I need to be an enrolled Apple Developer for 99€ to get those code signing certificates?

Nope, just an Apple ID of any kind. Add your account in the Xcode preferences, manage your account's certificates, and add an Apple Development Certificate. It's free for local development.

Then set your account as the team for both the `DevUtils` and `DevUtilsLauncher` targets, and it should build for you.

**Comment by micheld93** [comment]
Well, I found my problem. Thanks for all. There are more than two drop down menus for choosing the certificate. The third one is only visible when one changes the visibility settings in built setting from "basic" to "all". Small thing and takes a lot of time to find it.

**Comment by trungdq88** [comment]
Nice!

**Comment by trungdq88** [comment]
Nice! Thanks all for the helps!
