### ISSUE TITLE
[Bug] Instant Clipboard Replace Doesn't Recognize HTML for Formatting

### ISSUE THREAD

**Issue by calendee** [DevUtilsApp/DevUtils-app#80]
When triggering the Instant Keyboard Replace by opening DevUtils with the Hotkey or via the menu bar icon, it does not recognize HTML for formatting.

Example HTML on my clipboard:

```
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Chapter X</title>
		<link rel="shortcut icon" href="assets/images/favicon.svg"/>
	</head>
	<body>
		<section class="w-max p-4 space-x-4 mx-auto slide-container">
		</section>
		<main class="w-max space-x-2"></main>
	</body>
</html>
```

When I trigger DevUtils, it shows that "No tool was detected for this input (from clipboard)".

![CleanShot 2021-09-15 at 11 58 58](https://user-images.githubusercontent.com/57374/133477064-f167258a-e45a-451a-ac36-4b3b4beb0818.jpg)

**Comment by trungdq88** [comment]
Hi @calendee,

It's intended that the HTML input is not recognized. The reason is there are many tools that accept HTML string as an input (HTML format, HTML Preview, HTML to JSX, etc.).

I'm experimenting to improve this flow and I'm very excited to introduce it shortly. The new flow will be much shorter, more convenient, and keyboard-friendly. Stay tuned! 😄
